export interface TypeFileImport{
  Loan_No       : string;  
    Loan_Date     : string;
    SeriesSno     : number;
    SchemeSno     : number;
    Customer_Code : string;
    Customer_Name : string;
    Rel           : number;
    RelName	      : string;
    Address1      : string;
    Address2      : string;
    Address3      : string;
    Address4      : string;
    City		      : string;
    State		      : string;
    Pincode       : string;
    Area		      : string;
    Mobile		    : string;
    Phone         : string;
    Email         : string;
    Aadhar_No     : string;
    IGroup        : string;
    TotQty        : number;
    TotGrossWt    : number;
    TotNettWt     : number;
    TotPureWt     : number;
    Market_Value  : number;
    Principal	    : number
    Roi           : number;
    AdvIntDur     : number;
    AdvIntAmt	    : number
    DocChargesAmt : number
    Nett_Payable  : number
    Mature_Date   : string;
    Remarks       : string;
    ItemDetails   : string;
    PaymentModesXML : string;
    CompSno         : number;
    BranchSno       : number;
    CheckPartyParam : number;
}
