ALTER TABLE Party
ALTER COLUMN Party_Name VARCHAR(200);
GO

ALTER TABLE Party
ALTER COLUMN Print_Name VARCHAR(200);
GO

ALTER TABLE Party
ALTER COLUMN RelName VARCHAR(200);
GO

ALTER TABLE Party
ALTER COLUMN Address1 VARCHAR(200);
GO

ALTER TABLE Party
ALTER COLUMN Address2 VARCHAR(200);
GO

ALTER TABLE Party
ALTER COLUMN Address3 VARCHAR(200);
GO

ALTER TABLE Party
ALTER COLUMN Address4 VARCHAR(200);
GO

ALTER TABLE Party
ALTER COLUMN City VARCHAR(200);
GO

ALTER TABLE Party
ALTER COLUMN State VARCHAR(100);
GO

ALTER TABLE Ledgers
ALTER COLUMN Led_Name VARCHAR(200);
GO

ALTER TABLE Items
ALTER COLUMN Item_Name VARCHAR(200)
GO
